development:
  adapter: postgresql
  database: hartl_dev
  username: gjackson12
  password: 
  host: localhost

test:
  adapter: postgresql
  database: hartl_test
  username: gjackson12
  password: 
  host: localhost

production:
  adapter: postgresql
  database: 
  username: 
  password: 
  host: